import pytube
link = input(f"\n Enter The Youtube Video URL : ")
yt = pytube.YouTube(link)
print("\n Title:", yt.title)
print(" Author:", yt.author)
print(" Published date:", yt.publish_date.strftime("%Y-%m-%d"))
print(" Number of views:", yt.views)
print(" Length of video:", yt.length, "seconds")
yt.streams.get_highest_resolution().download()
print("\n Video successfullly downloaded from", link, "\n")
